# Generated by Django 3.2.13 on 2022-04-21 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 8, 39, 885016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 8, 39, 885016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 8, 8, 39, 885016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='routineresult',
            name='routine_result_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
